### ISSUE TITLE
template // Could not resolve "./controllers"

### ISSUE THREAD

**Issue by Adeynack** [nerdgeschoss/development-environment#8]
With a fresh project created from the template, `import './controllers';` in `app/javascript/application.ts` causes this error when starting the app (more specifically: `yarn build --watch`).

```
js     | ✘ [ERROR] Could not resolve "./controllers"
js     |
js     |     app/javascript/application.ts:4:7:
js     |       4 │ import './controllers';
js     |         ╵        ~~~~~~~~~~~~~~~
js     |
js     | 1 error
js     | [watch] build finished, watching for changes...
```

**Comment by Adeynack** [comment]
Commenting the import line makes the project at least start, but it may now be lacking something important.

**Comment by JensRavens** [comment]
looks like it's missing the index file there.
